"""
    comparisons/Translator/PhysicsAnnotation.jl

Solver-agnostic physical description of a benchmark problem.

Emitters for Spinach / QuTiP / SIMPSON / Krotov / qopt / Quandary consume a
`PhysicsAnnotation` and produce idiomatic native scripts in each target
program's own language. Round-trip: `build_ctrl_from_annotation(ann)` rebuilds
the matrix form (`MRControl` / `LindbladMRControl`) that Pulsar uses for
canonical re-evaluation via `grape_state_kernel` / `grape_lindblad_kernel`.

The annotation captures what a human uses when writing a Spinach / QuTiP /
SIMPSON script by hand — isotopes, offsets, couplings, CSAs, named spin states
— not raw matrices. Emitters never pattern-match on matrices.
"""

using LinearAlgebra

# ─── Component structs ────────────────────────────────────────────────────────

"""
    SpinAnnotation(isotope; offset_hz=0.0, csa=nothing, t1_s=Inf, t2_s=Inf)

Per-spin properties. `isotope` is a string key into `GYRO_MHZ_PER_T`
(`"1H"`, `"13C"`, ...). `offset_hz` is the reference chemical-shift offset
used at ensemble-center (the sweep adds deviations around this value).
"""
Base.@kwdef struct SpinAnnotation
    isotope   :: String
    offset_hz :: Float64                                   = 0.0
    csa       :: Union{Nothing,NamedTuple}                 = nothing
    t1_s      :: Float64                                   = Inf
    t2_s      :: Float64                                   = Inf
end

"""
    CouplingAnnotation(i, j; kind=:j_isotropic, value_hz, euler=(0,0,0))

Pairwise spin-spin coupling. `kind` is one of `:j_isotropic`, `:dipolar`, or
`:exchange`.  `value_hz` is the scalar (J or b) in Hz.
"""
Base.@kwdef struct CouplingAnnotation
    i        :: Int
    j        :: Int
    kind     :: Symbol                        = :j_isotropic
    value_hz :: Float64
    euler    :: NTuple{3,Float64}             = (0.0, 0.0, 0.0)
end

"""
    OffsetSweep(target_spin_idx, offsets_hz; weights=uniform)

Ensemble of drift Hamiltonians generated by applying each value in
`offsets_hz` to spin `target_spin_idx`.  `weights` must sum to 1.
Set `target_spin_idx = 0` to apply the offset to every spin simultaneously.
"""
struct OffsetSweep
    target_spin_idx :: Int
    offsets_hz      :: Vector{Float64}
    weights         :: Vector{Float64}
end

function OffsetSweep(target_spin_idx::Int, offsets_hz::AbstractVector;
                      weights::AbstractVector = fill(1.0 / length(offsets_hz),
                                                      length(offsets_hz)))
    length(offsets_hz) == length(weights) ||
        throw(ArgumentError("offsets_hz and weights must have the same length"))
    return OffsetSweep(target_spin_idx,
                        collect(Float64, offsets_hz),
                        collect(Float64, weights))
end

"""
    ControlAnnotation(name, spin_idx, axis, pwr_max_hz; channel_hz=0.0)

One physical RF channel.  `axis ∈ (:x, :y, :z)` picks the single-spin operator.
`pwr_max_hz` is the maximum RF amplitude in Hz (not rad/s).
"""
Base.@kwdef struct ControlAnnotation
    name       :: Symbol
    spin_idx   :: Int
    axis       :: Symbol
    pwr_max_hz :: Float64
    channel_hz :: Float64                = 0.0
end

"""
    TargetAnnotation(kind; initial_states, final_states, target_unitary=nothing,
                       target_per_drift=false)

Objective description.  `kind ∈ (:state_transfer, :universal_rotation,
:lindblad_state_transfer, :gate)`.

`initial_states` / `final_states` are `Vector{Vector{Symbol}}` — outer index
is state-pair index, inner index is per-spin single-spin state label
(`:Iz`, `:mIz`, `:Ix`, ...).  Composite states are built as Kronecker products.

If `target_per_drift` is `true`, the number of state pairs must equal the
ensemble size (drifts zipped to pairs 1:1 when the solver supports it;
matrix rebuild still uses the MRControl outer-product semantics).
"""
Base.@kwdef struct TargetAnnotation
    kind             :: Symbol
    initial_states   :: Vector{Vector{Symbol}}            = Vector{Symbol}[]
    final_states     :: Vector{Vector{Symbol}}            = Vector{Symbol}[]
    target_unitary   :: Union{Nothing,Matrix{ComplexF64}} = nothing
    target_per_drift :: Bool                               = false
end

# ─── Top-level annotation ─────────────────────────────────────────────────────

"""
    AbstractPhysicsAnnotation

Supertype for all solver-agnostic problem descriptions.  `PhysicsAnnotation`
covers NMR-style spin problems (BM01–BM06).  `TransmonAnnotation` (defined
in `TransmonAnnotation.jl`) covers QC-style superconducting-qubit problems
(BM07+).  Benchmark problems carry one or the other in their `physics` field.
"""
abstract type AbstractPhysicsAnnotation end

"""
    PhysicsAnnotation(; spins, couplings, sweep, controls, target, total_time_s,
                        n_time_steps, dt_s, method, max_iter, guess_seed,
                        b0_tesla)

Solver-agnostic description of one benchmark problem.  Emitters consume this.
Round-trip via [`build_ctrl_from_annotation`](@ref).
"""
Base.@kwdef struct PhysicsAnnotation <: AbstractPhysicsAnnotation
    spins         :: Vector{SpinAnnotation}
    couplings     :: Vector{CouplingAnnotation}          = CouplingAnnotation[]
    sweep         :: Union{Nothing,OffsetSweep}          = nothing
    controls      :: Vector{ControlAnnotation}
    target        :: TargetAnnotation
    total_time_s  :: Float64
    n_time_steps  :: Int
    dt_s          :: Float64
    method        :: Symbol                              = :lbfgs
    max_iter      :: Int                                  = 500
    guess_seed    :: Int                                  = 42
    b0_tesla      :: Float64                              = 14.1
end

# ─── Builders (Annotation → Pulsar matrix types) ──────────────────────────────

"""
    isotopes_vec(ann) -> Vector{String}

Return `[spin.isotope for spin in ann.spins]`.
"""
isotopes_vec(ann::PhysicsAnnotation) = [s.isotope for s in ann.spins]

n_spins(ann::PhysicsAnnotation) = length(ann.spins)

"""
    build_mr_system(ann) -> MRSpinSystem

Construct the Pulsar `MRSpinSystem` described by `ann`.
"""
build_mr_system(ann::PhysicsAnnotation)::MRSpinSystem = mr_system(isotopes_vec(ann))

"""
    build_state_vector(sys, symbols) -> Vector{ComplexF64}

Kronecker product of single-spin state vectors.  `symbols` has one entry per
spin in `sys`.  For a single-spin system, `symbols` may be a one-element vector.
"""
function build_state_vector(sys::MRSpinSystem, symbols::Vector{Symbol})::Vector{ComplexF64}
    length(symbols) == sys.n_spins ||
        throw(ArgumentError(
            "state symbols length $(length(symbols)) ≠ n_spins $(sys.n_spins)"))
    if sys.n_spins == 1
        return spin_state(sys, symbols[1])
    end
    singles = [spin_state(mr_system(sys.isotopes[k]), symbols[k]) for k in 1:sys.n_spins]
    return kron(singles...)
end

"""
    build_drifts(ann) -> Vector{Matrix{ComplexF64}}

Build the full ensemble of drift Hamiltonians described by `ann`.  Always
returns at least one drift (on-resonance, at `ann.spins[*].offset_hz`).
"""
function build_drifts(ann::PhysicsAnnotation)::Vector{Matrix{ComplexF64}}
    sys = build_mr_system(ann)
    base_offsets = [s.offset_hz for s in ann.spins]
    J            = _coupling_matrix(ann)

    if ann.sweep === nothing
        return [hamiltonian(sys; B0_tesla=ann.b0_tesla,
                             offsets_hz=base_offsets, couplings_hz=J)]
    end

    drifts = Matrix{ComplexF64}[]
    for Δf in ann.sweep.offsets_hz
        offs = copy(base_offsets)
        if ann.sweep.target_spin_idx == 0
            offs .+= Δf
        else
            offs[ann.sweep.target_spin_idx] += Δf
        end
        push!(drifts, hamiltonian(sys; B0_tesla=ann.b0_tesla,
                                    offsets_hz=offs, couplings_hz=J))
    end
    return drifts
end

function _coupling_matrix(ann::PhysicsAnnotation)::Matrix{Float64}
    N = n_spins(ann)
    J = zeros(Float64, N, N)
    for c in ann.couplings
        c.kind == :j_isotropic ||
            throw(ArgumentError(
                "_coupling_matrix: only :j_isotropic couplings are supported when " *
                "round-tripping via MRSpinSystem (got :$(c.kind)). Use the emitter " *
                "for solvers that handle anisotropic couplings natively."))
        J[c.i, c.j] = c.value_hz
        J[c.j, c.i] = c.value_hz
    end
    return J
end

"""
    build_operators(ann) -> Vector{Matrix{ComplexF64}}

Build the list of control Hamiltonians from `ann.controls`.
"""
function build_operators(ann::PhysicsAnnotation)::Vector{Matrix{ComplexF64}}
    sys = build_mr_system(ann)
    ops = Matrix{ComplexF64}[]
    for c in ann.controls
        sym = c.axis == :x ? :Ix :
              c.axis == :y ? :Iy :
              c.axis == :z ? :Iz :
              throw(ArgumentError("ControlAnnotation.axis must be :x, :y, or :z (got :$(c.axis))"))
        op = sys.n_spins == 1 ? spin_op(sys, sym) : spin_op(sys, sym, c.spin_idx)
        push!(ops, op)
    end
    return ops
end

"""
    build_state_pairs(ann) -> (Vector{Vector{ComplexF64}}, Vector{Vector{ComplexF64}})

Build `(rho_init, rho_targ)` lists ready to pass into `MRControl`.
"""
function build_state_pairs(ann::PhysicsAnnotation)
    sys   = build_mr_system(ann)
    inits = [build_state_vector(sys, syms) for syms in ann.target.initial_states]
    targs = [build_state_vector(sys, syms) for syms in ann.target.final_states]
    return inits, targs
end

"""
    build_pwr_levels(ann) -> Vector{Float64}

Collapse per-control `pwr_max_hz` values into the `pwr_levels` vector that
`MRControl` expects.  When every control has the same `pwr_max_hz`, returns a
single `[2π * pwr_max_hz]`; when they differ, returns `[2π * c.pwr_max_hz for c in controls]`.
"""
function build_pwr_levels(ann::PhysicsAnnotation)::Vector{Float64}
    pwrs = [c.pwr_max_hz for c in ann.controls]
    allequal = all(==(pwrs[1]), pwrs)
    return allequal ? [2π * pwrs[1]] : (2π .* pwrs)
end

"""
    build_jump_ops(ann) -> (Vector{Matrix{ComplexF64}}, Vector{Float64})

Build Lindblad jump operators and rates from per-spin T1/T2 in `ann.spins`.
Returns empty vectors when every spin has T1 = T2 = Inf (closed system).
"""
function build_jump_ops(ann::PhysicsAnnotation)
    sys = build_mr_system(ann)
    any_finite = any(isfinite(s.t1_s) || isfinite(s.t2_s) for s in ann.spins)
    any_finite || return (Matrix{ComplexF64}[], Float64[])

    all_equal = all(s -> s.t1_s == ann.spins[1].t1_s && s.t2_s == ann.spins[1].t2_s,
                     ann.spins)
    all_equal || throw(ArgumentError(
        "build_jump_ops: per-spin T1/T2 must be identical for the generic " *
        "rebuilder (got $(map(s -> (s.t1_s, s.t2_s), ann.spins))). " *
        "Customise the emitter for solvers that accept per-spin relaxation."))

    return mr_relaxation(sys; T1=ann.spins[1].t1_s, T2=ann.spins[1].t2_s)
end

# ─── Full ctrl rebuild ────────────────────────────────────────────────────────

"""
    build_ctrl_from_annotation(ann; kwargs...) -> MRControl or LindbladMRControl

Reconstruct the Pulsar matrix-form control object from the annotation.  Used
by round-trip tests and by `QuantumControlEmitter` (which stays in Julia).
Extra `kwargs` are forwarded to the `MRControl` / `LindbladMRControl` keyword
constructor (e.g. `verbose=false`).
"""
function build_ctrl_from_annotation(ann::PhysicsAnnotation; kwargs...)
    drifts    = build_drifts(ann)
    operators = build_operators(ann)
    rho_i, rho_t = build_state_pairs(ann)
    pwr_levels = build_pwr_levels(ann)
    pulse_dt   = fill(ann.dt_s, ann.n_time_steps)

    jump_ops, rates = build_jump_ops(ann)
    is_open = !isempty(jump_ops)

    if is_open
        return LindbladMRControl(
            drifts      = drifts,
            operators   = operators,
            jump_ops    = jump_ops,
            decay_rates = rates,
            rho_init    = rho_i,
            rho_targ    = rho_t,
            pwr_levels  = pwr_levels,
            pulse_dt    = pulse_dt,
            method      = ann.method,
            max_iter    = ann.max_iter,
            fidelity    = :square,
            verbose     = false;
            kwargs...,
        )
    else
        return MRControl(
            drifts     = drifts,
            operators  = operators,
            rho_init   = rho_i,
            rho_targ   = rho_t,
            pwr_levels = pwr_levels,
            pulse_dt   = pulse_dt,
            method     = ann.method,
            max_iter   = ann.max_iter,
            verbose    = false;
            kwargs...,
        )
    end
end
